version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_APP_NAME=${MONGO_APP_NAME}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    volumes:
      - ./backend:/app
      - ./gcp-credentials.json:/app/gcp-credentials.json:ro
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      target: build  # Use build stage for development
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=${FE_PORT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - BACKEND_URL=${BACKEND_URL}
      - UNSAFE_EVAL=${UNSAFE_EVAL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_DEBUG=${NEXTAUTH_DEBUG}
      - ENABLE_PROXY_UPLOADS=${ENABLE_PROXY_UPLOADS}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev:docker

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: