name: Deploy to GCP (Smart - Only Changed Components)

on:
  push:
    branches:
      - main

jobs:
  # Detect what changed
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      video-function: ${{ steps.changes.outputs.video-function }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Need at least 2 commits to compare

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/deploy*.yml'
            frontend:
              - 'frontend/**'
              - '.github/workflows/deploy*.yml'
            video-function:
              - 'cloud-functions/**'
              - '.github/workflows/deploy*.yml'

  # Deploy backend only if backend files changed
  deploy-backend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install Google Cloud CLI
        run: |
          echo "Installing Google Cloud CLI..."
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      - name: Deploy Backend
        run: |
          echo "🚀 Deploying Backend (files changed)"
          gcloud builds submit ./backend --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/turbulent-service
          
          # Encode the JSON to base64 to avoid parsing issues
          GCP_CREDS_B64=$(echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' | base64 -w 0)
          
          gcloud run deploy turbulent-service \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/turbulent-service \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account=${{ vars.GCP_SERVICE_ACCOUNT_NAME }} \
            --set-env-vars "MONGO_USER=${{ secrets.MONGO_USER }},MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }},MONGO_CLUSTER=${{ vars.MONGO_CLUSTER }},MONGO_APP_NAME=${{ vars.MONGO_APP_NAME }},MONGO_HOST=${{ vars.MONGO_HOST }},GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }},MONGO_DB_NAME=${{ vars.MONGO_DB_NAME }},GCS_BUCKET_NAME=${{ vars.GCS_BUCKET_NAME }}" \
            --set-env-vars "GOOGLE_APPLICATION_CREDENTIALS_JSON_B64=${GCP_CREDS_B64}" \
            --timeout=600s

  # Deploy frontend only if frontend files changed  
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install Google Cloud CLI
        run: |
          echo "Installing Google Cloud CLI..."
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      - name: Deploy Frontend
        run: |
          echo "🚀 Deploying Frontend (files changed)"
          gcloud builds submit ./frontend --tag gcr.io/${{ vars.GCP_PROJECT_ID }}/turbulent-frontend --project=${{ vars.GCP_PROJECT_ID }}
          gcloud run deploy turbulent-frontend \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/turbulent-frontend \
            --platform managed \
            --region us-central1 \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --allow-unauthenticated \
            --set-env-vars GOOGLE_CLIENT_ID=${{ vars.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }},NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }},NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }},NEXTAUTH_DEBUG=${{ vars.NEXTAUTH_DEBUG }},UNSAFE_EVAL=${{ vars.UNSAFE_EVAL }} \
            --timeout=600s

      - name: Make Frontend Public
        run: |
          gcloud run services add-iam-policy-binding turbulent-frontend \
            --region us-central1 \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --quiet

  # Deploy video function only if cloud function files changed
  deploy-video-function:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.video-function == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install Google Cloud CLI
        run: |
          echo "Installing Google Cloud CLI..."
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli

      - name: Deploy Video Processing Function
        run: |
          echo "🚀 Deploying Video Function (files changed)"
          
          # Build MongoDB URI from secrets/vars
          MONGODB_URI="mongodb+srv://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@${{ vars.MONGO_HOST }}/${{ vars.MONGO_DB_NAME }}?retryWrites=true&w=majority&appName=${{ vars.MONGO_APP_NAME }}"
          
          # Deploy the Cloud Function from Dockerfile
          gcloud functions deploy video-processor \
            --gen2 \
            --runtime=python311 \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --region=us-central1 \
            --source=./cloud-functions/video-processor \
            --entry-point=process_video \
            --trigger-event-filters="type=google.cloud.storage.object.v1.finalized" \
            --trigger-event-filters="bucket=${{ vars.GCS_BUCKET_NAME }}" \
            --set-env-vars="GCS_BUCKET_NAME=${{ vars.GCS_BUCKET_NAME }},MONGODB_URI=${MONGODB_URI},API_BASE_URL=${{ vars.NEXT_PUBLIC_API_URL }}" \
            --memory=2GiB \
            --timeout=540s \
            --max-instances=5 \
            --cpu=1 \
            --service-account="${{ vars.GCP_SERVICE_ACCOUNT_NAME }}"

  # Summary job to show what was deployed
  deployment-summary:
    runs-on: ubuntu-latest
    needs: [detect-changes, deploy-backend, deploy-frontend, deploy-video-function]
    if: always()
    steps:
      - name: Deployment Summary
        run: |
          echo "## Deployment Summary 📋"
          echo "Backend Changed: ${{ needs.detect-changes.outputs.backend }}"
          echo "Frontend Changed: ${{ needs.detect-changes.outputs.frontend }}"
          echo "Video Function Changed: ${{ needs.detect-changes.outputs.video-function }}"
          echo ""
          if [ "${{ needs.detect-changes.outputs.backend }}" == "true" ]; then
            echo "✅ Backend deployed"
          else
            echo "⏭️ Backend skipped (no changes)"
          fi
          
          if [ "${{ needs.detect-changes.outputs.frontend }}" == "true" ]; then
            echo "✅ Frontend deployed"
          else
            echo "⏭️ Frontend skipped (no changes)"
          fi
          
          if [ "${{ needs.detect-changes.outputs.video-function }}" == "true" ]; then
            echo "✅ Video Function deployed"
          else
            echo "⏭️ Video Function skipped (no changes)"
          fi
